server.port: 9080
spring:
  application:
    name: products-api
    admin:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/data/featuretoggles;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialize: false
    hikari:
      maximumPoolSize: 8
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        generate_statistics: true
    hibernate:
      jdbc:
        time_zone: UTC
      ddl-auto: create

  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    org:
      michaeldecourci:
        feature: DEBUG
      springframework: INFO
      hibernate:
        SQL: trace
        type: trace